In [2]:
import imutils
import cv2 as cv
from transform import four_point_transform
from skimage.filters import threshold_local
import numpy as np

In [3]:
image = cv.imread('../images/bill_supermarket.jpg')

# image.shape

ratio = image.shape[0]/500.0

orig = image.copy()
image = imutils.resize(image, height=500)

gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
gray = cv.GaussianBlur(gray, (5,5),0)
edged = cv.Canny(gray, 100,200)

print("edge")
cv.imshow("image",image)
cv.imshow("edged",edged)
# edged = cv.Canny(gray, 100,200)
# cv.imshow("edged",edged)
cv.waitKey(0)
cv.destroyAllWindows()

edge


In [22]:
image.shape

(500, 631, 3)

In [23]:
orig.shape

(633, 800, 3)

In [12]:
cv.GaussianBlur?

In [4]:
im2, contours, hierarchy = cv.findContours(edged.copy(),cv.RETR_TREE,cv.CHAIN_APPROX_SIMPLE)

In [6]:
cv.drawContours(im2, contours[0], -1, (0,255,0), 3)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [29]:
imutils.is_cv2?

In [30]:
contours[0]

array([[[296, 463]],

       [[297, 464]],

       [[297, 465]],

       [[298, 465]],

       [[299, 466]],

       [[301, 464]],

       [[300, 464]],

       [[300, 465]],

       [[299, 466]],

       [[297, 464]],

       [[297, 463]]], dtype=int32)

In [32]:
len(contours)

271

In [33]:
c = sorted(contours[0] , key=cv.contourArea, reverse=True)[:5]

In [7]:
cv.imshow("image", im2)
cv.waitKey(0)
cv.destroyAllWindows()

In [17]:
import numpy as np
import cv2
    
im = cv2.imread('../images/bill_supermarket.jpg')
imgray = cv2.cvtColor(im,cv2.COLOR_BGR2GRAY)
ret,thresh = cv2.threshold(imgray,127,255,0)
im2, contours, hierarchy = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

In [18]:
im3  = im.copy()
cv2.drawContours(im3, contours, -1, (0,255,0), 3)
cv2.imshow("image",im3)

In [13]:
contours[4]

array([[[793, 631]],

       [[793, 632]],

       [[794, 631]]], dtype=int32)

In [14]:
contours[3]

array([[[ 32, 632]]], dtype=int32)

In [15]:
contours[5]

array([[[787, 631]]], dtype=int32)

In [16]:
contours[6]

array([[[797, 629]],

       [[796, 630]],

       [[796, 632]],

       [[797, 632]]], dtype=int32)

In [14]:
import cv2
import numpy as np
import imutils
image = cv2.imread('../images/image2.jpg')
image = imutils.resize(image, height=500)
blurred = cv2.pyrMeanShiftFiltering(image, 10,20)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
# using GaussianBlur for making the image blur
# blurred = cv2.GaussianBlur(gray, (5, 5), 0)
cv2.imshow("blurred", blurred)


ret, threshold = cv2.threshold(gray, 0,255,cv2.THRESH_BINARY+cv2.THRESH_OTSU)
# edge detection in the image
# canny = cv2.Canny(blurred, 100, 200)

# finding the contourse which comes in 2nd parameter of the tuple
(_, cnts, _) = cv2.findContours(threshold, cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)

print ("Contours in the image, %d" % (len(cnts)))

shape = image.copy()
cv2.drawContours(shape, cnts, -1, (0, 255, 0), 2)
cv2.imshow("All contours", shape)


shape2  = image.copy()
# now i want to get the biggest contour
cnts = sorted(cnts, key=cv2.contourArea, reverse=True)[:1]
cv2.drawContours(shape2, cnts, -1, (255,0,0),2)
cv2.imshow("biggest",shape2)

# printing the area
# per = 0
# ind = 0
# for index,c in enumerate(cnts):
    
#     peri = cv2.arcLength(c, True)
#     print("{} {}".format(index, peri))
#     if peri > per:
#         per = peri
#         ind = index
# print(ind)
# approx = cv2.approxPolyDP(c,  0.001*per, True)
# screenCnt2 = approx
# if our approximated contour has four points, then we
# can assume that we have found our screen
# if len(approx) == 4:
#     print("doing operation on frame{}".format(index))
#     screenCnt2 = approx
#     break
    
    
# shape3 = image.copy()
# cv2.drawContours(shape3, [screenCnt2],-1, (0,0,255),2),
# cv2.imshow("final",shape3)
cv2.waitKey(0)
cv2.destroyAllWindows()

Contours in the image, 284


## Using another approach

In [24]:
import cv2
import numpy as np
import imutils
from transform import four_point_transform
from skimage.filters import threshold_local


image = cv2.imread('../images/bill_supermarket.jpg')
orig= image.copy()
ratio = image.shape[0]/500.0
image = imutils.resize(image, height=500)
blurred = cv2.pyrMeanShiftFiltering(image, 10,20)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)



ret, threshold = cv2.threshold(gray, 0,255,cv2.THRESH_BINARY+cv2.THRESH_OTSU)
(_, cnts, _) = cv2.findContours(threshold, cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)

print ("Contours in the image, %d" % (len(cnts)))

shape = image.copy()
cv2.drawContours(shape, cnts, -1, (0, 255, 0), 2)



shape2  = image.copy()

# now i want to get the biggest contour
cnts = sorted(cnts, key=cv2.contourArea, reverse=True)[:5]
cv2.drawContours(shape2, cnts, 0, (0,0,255),2)

# abc = cnts[0]


for c in cnts:
    # approximate the contour
    peri = cv2.arcLength(c, True)
    approx = cv2.approxPolyDP(c, 0.02 * peri, True)
 
    # if our approximated contour has four points, then we
    # can assume that we have found our screen
    if len(approx) == 4:
        print("Got the box....inside the if ")
        screenCnt = approx
        break

shape3 = image.copy()
cv2.drawContours(shape3, [screenCnt], -1, (0, 0, 255), 2)




warped = four_point_transform(orig, screenCnt.reshape(4, 2) * ratio)
 
# convert the warped image to grayscale, then threshold it
# to give it that 'black and white' paper effect
warped = cv2.cvtColor(warped, cv2.COLOR_BGR2GRAY)
T = threshold_local(warped, 11, offset = 10, method = "gaussian")
warped = (warped > T).astype("uint8") * 255
 

# show all the images
cv2.imshow("Original image", orig )
cv2.imshow("blurred image", blurred)
cv2.imshow("All contours", shape)
cv2.imshow("biggest contour",shape2)
cv2.imshow("Box", shape3)
cv2.imshow("Final Scanned", warped)


cv2.waitKey(0)
cv2.destroyAllWindows()


Contours in the image, 496
Got the box....inside the if 


In [13]:
screenCnt.shape

(4, 1, 2)

In [21]:
warped.shape

(563, 400)

In [22]:
orig.shape

(633, 800, 3)